### ISSUE TITLE
Hyperf3兼容

### ISSUE THREAD

**Issue by DongyunLee** [myxiaoao/hyperf-pest#1]
大佬有时间兼容下 hyperf3.0 和 php8.1 么

**Comment by myxiaoao** [comment]
不好意思，最近是真没时间。

**Comment by DongyunLee** [comment]
大佬，我看更新了，要不发个 release？

**Comment by myxiaoao** [comment]
更新了，但是不支持 pest 2，因为默认的 hyperf/testing 还是用的 phpunit 9 的版本。pest 2 需要 phpunit 10 以上的版本。 @DongyunLee

**Comment by DongyunLee** [comment]
收到，已经帮很大忙了，感谢！

**Comment by BadJacky** [comment]
@DongyunLee  目前 hy 的 phpunit 依赖版本已经改为 phpunit10 辣，大佬有时间搞么？

**Comment by DongyunLee** [comment]
> @DongyunLee 目前 hy 的 phpunit 依赖版本已经改为 phpunit10 辣，大佬有时间搞么？

帮你 @ 正主 @myxiaoao 👀

**Comment by BadJacky** [comment]
@DongyunLee  目前 hyperf 还未发布稳定版本支持 phpunit10

**Comment by myxiaoao** [comment]
@DongyunLee @BadJacky 官方 3.1 已经默认支持 pest 了, https://github.com/hyperf/hyperf/releases/tag/v3.1.0

**Comment by DongyunLee** [comment]
> @DongyunLee @BadJacky 官方 3.1 已经默认支持 pest 了, https://github.com/hyperf/hyperf/releases/tag/v3.1.0

好的，感谢给我们带来了非常好的 tdd 使用体验，进步离不开每一个贡献者！感谢！致敬！

**Comment by BadJacky** [comment]
@myxiaoao 官方提供的支持目前在 PHP8.3 with swoole  5.1.1 for Mac 下无法正常工作，大概率我们还是要继续。

**Comment by DongyunLee** [comment]
> @myxiaoao 官方提供的支持目前在 PHP8.3 with swoole 5.1.1 for Mac 下无法正常工作，大概率我们还是要继续。

有看这个 issue 吗？
[https://github.com/hyperf/hyperf/issues/3842#issuecomment-883280175](https://github.com/hyperf/hyperf/issues/3842#issuecomment-883280175)

**Comment by BadJacky** [comment]
> > @myxiaoao 官方提供的支持目前在 PHP8.3 with swoole 5.1.1 for Mac 下无法正常工作，大概率我们还是要继续。
> 
> 有看这个 issue 吗？ [hyperf/hyperf#3842 (comment)](https://github.com/hyperf/hyperf/issues/3842#issuecomment-883280175)

多谢多谢，之前使用的 prepend 文件是 
```php
<?php
require_once __DIR__ . '/../vendor/autoload.php';

defined('BASE_PATH') or define('BASE_PATH', dirname(__DIR__, 1));

(function () {
    \Hyperf\Di\ClassLoader::init();

    \Hyperf\Context\ApplicationContext::setContainer(
        new \Hyperf\Di\Container((new \Hyperf\Di\Definition\DefinitionSourceFactory())())
    );
    
    // $container->get(Hyperf\Contract\ApplicationInterface::class);
})();

```
看来是我弄错了

**Comment by DongyunLee** [comment]
> > > @myxiaoao 官方提供的支持目前在 PHP8.3 with swoole 5.1.1 for Mac 下无法正常工作，大概率我们还是要继续。
> > 
> > 
> > 有看这个 issue 吗？ [hyperf/hyperf#3842 (comment)](https://github.com/hyperf/hyperf/issues/3842#issuecomment-883280175)
> 
> 多谢多谢，之前使用的 prepend 文件是
> 
> ```
> <?php
> require_once __DIR__ . '/../vendor/autoload.php';
> 
> defined('BASE_PATH') or define('BASE_PATH', dirname(__DIR__, 1));
> 
> (function () {
>     \Hyperf\Di\ClassLoader::init();
> 
>     \Hyperf\Context\ApplicationContext::setContainer(
>         new \Hyperf\Di\Container((new \Hyperf\Di\Definition\DefinitionSourceFactory())())
>     );
>     
>     // $container->get(Hyperf\Contract\ApplicationInterface::class);
> })();
> ```
> 
> 看来是我弄错了

但是看起来确实还是有一些问题，比如不明原因报错“API 需要运行在协程环境中”啥的，还是得再踩踩坑

**Comment by BadJacky** [comment]
> > > > @myxiaoao 官方提供的支持目前在 PHP8.3 with swoole 5.1.1 for Mac 下无法正常工作，大概率我们还是要继续。
> > > 
> > > 
> > > 有看这个 issue 吗？ [hyperf/hyperf#3842 (comment)](https://github.com/hyperf/hyperf/issues/3842#issuecomment-883280175)
> > 
> > 
> > 多谢多谢，之前使用的 prepend 文件是
> > ```
> > <?php
> > require_once __DIR__ . '/../vendor/autoload.php';
> > 
> > defined('BASE_PATH') or define('BASE_PATH', dirname(__DIR__, 1));
> > 
> > (function () {
> >     \Hyperf\Di\ClassLoader::init();
> > 
> >     \Hyperf\Context\ApplicationContext::setContainer(
> >         new \Hyperf\Di\Container((new \Hyperf\Di\Definition\DefinitionSourceFactory())())
> >     );
> >     
> >     // $container->get(Hyperf\Contract\ApplicationInterface::class);
> > })();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看来是我弄错了
> 
> 但是看起来确实还是有一些问题，比如不明原因报错“API 需要运行在协程环境中”啥的，还是得再踩踩坑

已经解决了，同时可以使用 pest ^2.x 的版本。不过遇到了一些比较奇怪的问题。
1. 在某些情况下，会出现引入存在的文件的时候提示文件不存在的错误，但是如果在引入时手动 usleep 或者 var_dump 就可以解决问题，但是问题无法百分百复现
2. 需要变更 phpunit.xml 文件，同时也要修改对应的测试命令。
3. 我已经完全遗弃了直接使用 phpunit 的任何操作，例如 composer.json，同时我把 test 目录删掉了，仅保留了 pest --init 生成的 pests 目录。

我今天要测验一下有没有其他的隐式问题，如果没有其他隐式问题，我会贴出具体的变更内容。
